name: fastapi-crud
services:
  fastapi:
    public: true
    image: youngestdev/fastapi-crud:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
