name: fastapi-crud
services:
  fastapi:
    public: true
    image: okteto.dev/fastapi-crud:latest
    build: .
    replicas: 1
    ports:
      - 8080
    environment:
      - DB_HOST=mongodb://${DB_USER}:${DB_PASSWORD}@localhost:27017
    resources:
      cpu: 100m
      memory: 128Mi

  mongodb:
     image: bitnami/mongodb:latest
     volumes:
       - /data/db



